platform :ios, '13.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # 添加以下兼容性设置
    target.build_configurations.each do |config|
      # 解决 _symbol_aliasing.h 错误
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'LIBC_NO_LIBCRAP=1'
      
      # 设置 C 语言标准为 GNU99
      config.build_settings['GCC_C_LANGUAGE_STANDARD'] = 'gnu99'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++0x'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      
      # 解决模块导入问题
      config.build_settings['CLANG_ENABLE_MODULES'] = 'YES'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      
      # 排除不支持的架构
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386'
    end
  end
  
  # Fix GeneratedPluginRegistrant.m for Xcode 15 compatibility
  generated_file = File.join(File.dirname(__FILE__), 'Runner', 'GeneratedPluginRegistrant.m')
  if File.exist?(generated_file)
    content = File.read(generated_file)
    
    # Comment out problematic plugin imports
    content.gsub!(/#if __has_include\(<file_save_directory\/FileSaveDirectoryPlugin\.h>\).*?#endif/m, '// file_save_directory - commented out for Xcode 15 compatibility')
    content.gsub!(/#if __has_include\(<path_provider_foundation\/PathProviderPlugin\.h>\).*?#endif/m, '// path_provider_foundation - commented out for Xcode 15 compatibility')
    content.gsub!(/#if __has_include\(<shared_preferences_foundation\/SharedPreferencesPlugin\.h>\).*?#endif/m, '// shared_preferences_foundation - commented out for Xcode 15 compatibility')
    content.gsub!(/#if __has_include\(<url_launcher_ios\/URLLauncherPlugin\.h>\).*?#endif/m, '// url_launcher_ios - commented out for Xcode 15 compatibility')
    
    # Comment out registration calls
    content.gsub!(/  \[FileSaveDirectoryPlugin registerWithRegistrar:.*?\];/, '  // [FileSaveDirectoryPlugin registerWithRegistrar:...];')
    content.gsub!(/  \[PathProviderPlugin registerWithRegistrar:.*?\];/, '  // [PathProviderPlugin registerWithRegistrar:...];')
    content.gsub!(/  \[SharedPreferencesPlugin registerWithRegistrar:.*?\];/, '  // [SharedPreferencesPlugin registerWithRegistrar:...];')
    content.gsub!(/  \[URLLauncherPlugin registerWithRegistrar:.*?\];/, '  // [URLLauncherPlugin registerWithRegistrar:...];')
    
    File.write(generated_file, content)
    puts "Fixed GeneratedPluginRegistrant.m for Xcode 15 compatibility"
  end
end
